### PR TITLE
Installing client middleware on first connect.

### PR DESCRIPTION
**Pull request by roberthoner**
#90

I also added support for anonymous services (i.e., `Class.new(Rester::Service)`), which was helpful in this case for testing.

### CODE REVIEW

**Comment by roberthoner** [comment]
Weird... the build because bundle installing is failing on ruby 2.1.8.  It's not even getting to the actual tests.  It can't build native sqlite3 extensions.

image

**Comment by roberthoner** [comment]
I can confirm this is an issue with the travis-ci build environment. Something changed because old builds that had passed are failing for the same reason. This is only affecting ruby 2.1.8.

**Comment by roberthoner** [comment]
I replaced ruby 2.1.8 with ruby 2.1.7 and it worked.  There shouldn't be any material difference between those two versions, just some weird environment issue with travis ci.

I also confirmed that I was able to bundle install with 2.1.8 on my local environment on OSX, so I there's no inherent incompatibility with 2.1.8.

**Comment by kayvonghaffari** [comment]
Looks good!

**Pull request merged**
